#!/bin/sh

red='\e[0;31m' # Red
grn='\e[0;32m' # Green
ylw='\e[0;33m' # Yellow
pur='\e[0;35m' # Purple
cyn='\e[0;36m' # Cyan
wht='\e[0;37m' # White
def='\e[m'     # default color

print_colored() {
    bash -c "echo -e $1"
}



echo
print_colored "\"                   ${red}J ${grn}A ${ylw}C ${pur}K ${cyn}P ${wht}O ${red}T ${grn}!!${def}\""
echo
print_colored "\"This shell script runs with ${red}`whoami`${def}'s permissions:\""
echo
print_colored "\"${grn}$ id${def}\""
id
echo
